version: '3.8'

services:

  DataDashboard:
    build: ./DataDashboard/
    image: datadashboard_img
    container_name: datadashboard_cntr

    ports:
      - 2051:2051

    stdin_open: true # docker run -i
    tty: true        # docker run -t

    volumes:
      - ./DataDashboard:/DataDashboard_app
  
  #database
  mongodb:

    image: mongo:6.0
    container_name: mongodb
    restart: unless-stopped

    environment: # setting up required env variables to access mongodb
      MONGO_INITDB_ROOT_USERNAME: ${MongoLogin}
      MONGO_INITDB_ROOT_PASSWORD: ${MongoPWD}

    ports:
      - 27017:27017

    user: "root" 

    volumes: # where the db directory is mounted to allow the data to persist.
    - ./database_data:/data/db

