version: '3.8'

services:

  DataDashboard:
    build: ./DataDashboard/
    image: datadashboard_img
    container_name: datadashboard_cntr

    ports:
      - 2051:2051

    stdin_open: true # docker run -i
    tty: true        # docker run -t

    volumes:
      - ./DataDashboard:/DataDashboard_app

